### ISSUE TITLE
Deleting resource taxonomy terms

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#10]
63. Deleting Resource Taxonomy terms 

--------- Forwarded message ----------
From: Jake Lake <jlake@oxiem.com>
Date: Wed, Sep 23, 2015 at 11:41 AM
Subject: Re: Question about Smartling
To: Matt Hazen <mhazen@stone-rabbit.com>
Cc: Crystal Olig <crystal@oxiem.com>, Nate Hallum <nhallum@stone-rabbit.com>

Matt,

Sorry for the delay - I don’t know that error specifically but I will look into it because they want me to update the Smartling module here this week.  I had actually made some code changes to the module to get it to work properly with field collections so I’ll test the deleting of the resource type vocab and see if I can hit your error locally and fix it too.  Go ahead and leave this to me since I’ve already played with that module (it’s really ugly in there).

Thanks,
//Jake

—
Sent from Mailbox

On Mon, Sep 21, 2015 at 2:55 PM, Matt Hazen <mhazen@stone-rabbit.com> wrote:
Hi Jake,

I’m having some trouble deleting taxonomy terms from the Resource Type vocabulary on Polyone.oxiemsites.com. On there, it just shows the white screen of death when you perform a delete.

On my dev server, I see this PHP Fatal Error:
Fatal error: Call to undefined method EntityValueWrapper::getBundle() in /home/polyonedev/public_html/sites/all/modules/contrib/smartling/lib/Drupal/smartling/Forms/GenericEntitySettingsForm.php on line 83

Is this something you’ve seen before? Do you know a way to resolve it? I didn’t see it in the Smartling Issue Queue.

For the time being, I was able to set up a VBO page to “bulk” delete the items we need to get rid of, so it’s not an emergency, but if you’d seen it before, I thought we could try to solve it.

Thanks,
Matt

**Comment by crystalolig** [comment]
I saw this was possible last week; closing.
