### ISSUE TITLE
Resource center front end issue

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#11]
65. Resource Center front end issue -
There error message being reported here is part of a “goupward_util” module, which I think Jake made. I can take a look at it, but it may be better to have him take a look.

Warning: usort() expects parameter 1 to be array, string given inproductFinder() (line885 of/var/www/vhosts/polyone.oxiemsites.com/httpdocs/sites/all/modules/custom/goupward_util/goupward_util.module)

**Comment by crystalolig** [comment]
Jake, what about the other error we were seeing? I was able to replicate by adding filters, submitting, then removing a filter and submitting again?

**Comment by crystalolig** [comment]
If this is a SR thing I will happily send to them...

**Comment by crystalolig** [comment]
sent to SR
