### ISSUE TITLE
Product Detail Resources Table

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#22]
80. Product Detail - If no resources populate, tab should not show up

**Comment by crystalolig** [comment]
http://polyone.oxiemsites.com/products/films/korad-weatherable-acrylic-films - still see empty tab here

**Comment by crystalolig** [comment]
This is what I see in Firefox. No product table or resources is there and a little blank spot shows up.

![uploads/2dcffff3-f3e1-468f-8076-c7437544a01d/resourcestab.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2dcffff3-f3e1-468f-8076-c7437544a01d%2Fresourcestab.png)
