### ISSUE TITLE
Product Listings Issue

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#26]
84. /node/360 is showing up twice in listings panel, all content entry appears correct

**Comment by lakesta** [comment]
Millenium V Durable Sheet

**Comment by lakesta** [comment]
![uploads/544b613d-0cb1-4a51-8c06-3835e8a5a28e/Screen Shot 2015-10-05 at 11.11.13 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F544b613d-0cb1-4a51-8c06-3835e8a5a28e%2FScreen+Shot+2015-10-05+at+11.11.13+AM.png)

![uploads/54454655-b6be-445c-8418-b03c719e8c10/Screen Shot 2015-10-05 at 11.11.28 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F54454655-b6be-445c-8418-b03c719e8c10%2FScreen+Shot+2015-10-05+at+11.11.28+AM.png)

![uploads/56199a80-4f6a-4ac1-9dff-c4b5868f209e/Screen Shot 2015-10-05 at 11.11.43 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F56199a80-4f6a-4ac1-9dff-c4b5868f209e%2FScreen+Shot+2015-10-05+at+11.11.43+AM.png)

**Comment by crystalolig** [comment]
I deleted it from Menu. Sorry. I swore we tried that before.
