### ISSUE TITLE
Contact Lander Filter

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#30]
89. CONTACT lander - Add “Product Family” as a drop down - the field is already present on back end.
Suggest you place in 2nd row, under the 1st column.

Which is easier - change State to Facility type or add a new field on front end to include Facility?

**Comment by crystalolig** [comment]
Hi Jake,
Verified with client. Desire is to NOT sure Product Family, so scratch that. Let's talk on alternatives.
