### ISSUE TITLE
The whole empty image cell thing in Chrome is making them craze-balls. It's fixable, right?

### ISSUE THREAD

**Issue by crystalolig** [lakesta/oxiem-p1#42]

**Comment by crystalolig** [comment]
![uploads/622446a7-fbac-4c3b-ab1f-92a2c4a9a281/chrome.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F622446a7-fbac-4c3b-ab1f-92a2c4a9a281%2Fchrome.png)

**Comment by lakesta** [comment]
FIXXXXXXED

**Comment by crystalolig** [comment]
still seeing on dev and stage...and I swore was gone

**Comment by lakesta** [comment]
What page did you see this happening on?  Last time I fixed it I fixed it on the idea pages and that code is still there and working.  Thanks.

**Comment by crystalolig** [comment]
http://polyone.oxiemsites.com/products/plasticizers

On Sun, Oct 25, 2015 at 9:43 PM, Jake <notifications@github.com> wrote:

> What page did you see this happening on? Last time I fixed it I fixed it
> on the idea pages and that code is still there and working. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/42#issuecomment-150999587>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield

**Comment by lakesta** [comment]
OK so that's a megalander with no logo I believe so let me add a condition for that logo not existing.

**Comment by crystalolig** [comment]
thank you

On Mon, Oct 26, 2015 at 9:48 AM, Jake <notifications@github.com> wrote:

> OK so that's a megalander with no logo I believe so let me add a condition
> for that logo not existing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/42#issuecomment-151138876>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield

**Comment by crystalolig** [comment]
checked again looks good
