### ISSUE TITLE
Remove content in the URL

### ISSUE THREAD

**Issue by crystalolig** [lakesta/oxiem-p1#54]
http://polyone.oxiemsites.com/content/polyone-corporation-announces-quarterly-dividend

**Comment by lakesta** [comment]
Remove it and replace it with what, /news or something?

**Comment by lakesta** [comment]
That URL seems to actually take me to http://polyone.oxiemsites.com/investor-center/news/polyone-corporation-announces-quarterly-dividend - did someone already take care of this, SR?

**Comment by crystalolig** [comment]
Yes I gave that one to them. Anything in the Ready column went to them.

On Sat, Oct 10, 2015 at 11:07 AM, Jake <notifications@github.com> wrote:

> That URL seems to actually take me to
> http://polyone.oxiemsites.com/investor-center/news/polyone-corporation-announces-quarterly-dividend
> - did someone already take care of this, SR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/54#issuecomment-147096247>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield
