### ISSUE TITLE
News image sizes add new one

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#6]
53. Check news imagery sizes - 
Thumbnail - for streams/footer ish area, Mid-sized feature for Featured size- News/Home ~400, - 
Content Width - full body width for within the article

Let SR know where to replace and what proper images to use.

**Comment by crystalolig** [comment]
I took care of this. 
http://project.oxiem.com/public/index.php?path_info=projects/polyone27659-polyone-website-redesignreb-1/tasks/459
