### ISSUE TITLE
Industry SubDetail pages

### ISSUE THREAD

**Issue by crystalolig** [lakesta/oxiem-p1#62]
Something going wrong in body area. Text is input correctly from what I can tell: http://polyone.oxiemsites.com/node/1527/

**Comment by lakesta** [comment]
Fixed, the body of featured story #1 had this in it:

<style type="text/css">
</style>

**Comment by crystalolig** [comment]
Oh I only looked at the main body wziwig


On Wed, Oct 14, 2015 at 9:31 AM, Jake <notifications@github.com> wrote:

> Fixed, the body of featured story #1
> <https://github.com/lakesta/oxiem-p1/issues/1> had this in it:
> 
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/62#issuecomment-148067683>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield
