### ISSUE TITLE
Ensure logged-in interface (black main nav) does not overlap utility/top portion of the site

### ISSUE THREAD

**Issue by crystalolig** [lakesta/oxiem-p1#74]
Jake, not entirely sure this is possible without adding accidental headroom on the front end of the site, but could you advise?

**Comment by lakesta** [comment]
I just disabled the toolbar.  When you login now you should be taken to /admin where you can still get to everything that was in the menu but this will no longer effect the pages.

**Comment by crystalolig** [comment]
Oh I think that will freak them out; they use shortcuts and stuff pretty
extensively and the whole reason they wanted the toolbar not to overlap the
util was that they navigate the site as a front end user for most editing.
I'd rather just tell them it will have to overlap, so please enable it
again.

On Sun, Oct 25, 2015 at 10:14 PM, Jake <notifications@github.com> wrote:

> I just disabled the toolbar. When you login now you should be taken to
> /admin where you can still get to everything that was in the menu but this
> will no longer effect the pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/74#issuecomment-151002776>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield

**Comment by lakesta** [comment]
OK, I was looking at a way to make it left aligned rather than top aligned so let me continue that search then instead.

**Comment by crystalolig** [comment]
It's honestly not a huge deal :)

On Mon, Oct 26, 2015 at 9:46 AM, Jake <notifications@github.com> wrote:

> OK, I was looking at a way to make it left aligned rather than top aligned
> so let me continue that search then instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lakesta/oxiem-p1/issues/74#issuecomment-151138353>.
>



-- 
CRYSTAL OLIG  interactive director
crystal@goupward.com • t  614.787.6676
cleveland • columbus • dayton • springfield
