### ISSUE TITLE
Footer hardcoded

### ISSUE THREAD

**Issue by lakesta** [lakesta/oxiem-p1#9]
62. Footer links hardcoded?
“It appears that the text at the very bottom, under the rainbow line is hard coded into the template. I had looked through all the possible locations where I might find a place to edit it without luck. The same for the social media buttons in the far right column.”

Yes, it is hardcoded and I never revisited it.  Let me think about how to move forward on that.

**Comment by crystalolig** [comment]
Assinged to SR today
